//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusAlina.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CircusAlinaTahEntities1 : DbContext
    {
        public CircusAlinaTahEntities1()
            : base("name=CircusAlinaTahEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acts> Acts { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<ShowActs> ShowActs { get; set; }
        public virtual DbSet<ShowInventory> ShowInventory { get; set; }
        public virtual DbSet<Shows> Shows { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<Tours> Tours { get; set; }
        public virtual DbSet<TourShows> TourShows { get; set; }
    }
}
