//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusAlina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SaleID { get; set; }
        public int TicketID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public string PaymentMethod { get; set; }
        public string CustomerName { get; set; }
    
        public virtual Tickets Tickets { get; set; }
    }
}
