//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusAlina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowActs
    {
        public int ShowActID { get; set; }
        public Nullable<int> ShowID { get; set; }
        public Nullable<int> ActID { get; set; }
    
        public virtual Acts Acts { get; set; }
        public virtual Shows Shows { get; set; }
    }
}
